/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DisplayDate: typeof import('./components/DisplayDate.vue')['default']
    ExploreContainer: typeof import('./components/ExploreContainer.vue')['default']
    IonAccordion: typeof import('@ionic/vue')['IonAccordion']
    IonAccordionGroup: typeof import('@ionic/vue')['IonAccordionGroup']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonChip: typeof import('@ionic/vue')['IonChip']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFab: typeof import('@ionic/vue')['IonFab']
    IonFabButton: typeof import('@ionic/vue')['IonFabButton']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonNav: typeof import('@ionic/vue')['IonNav']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonProgressBar: typeof import('@ionic/vue')['IonProgressBar']
    IonRefresher: typeof import('@ionic/vue')['IonRefresher']
    IonRefresherContent: typeof import('@ionic/vue')['IonRefresherContent']
    IonSelect: typeof import('@ionic/vue')['IonSelect']
    IonSelectOption: typeof import('@ionic/vue')['IonSelectOption']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToast: typeof import('@ionic/vue')['IonToast']
    IonToggle: typeof import('@ionic/vue')['IonToggle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    Pagination: typeof import('./components/Pagination.vue')['default']
    ProductDetail: typeof import('./components/product/ProductDetail.vue')['default']
    ProductDetails: typeof import('./components/product/ProductDetails.vue')['default']
    ProductList: typeof import('./components/product/ProductList.vue')['default']
    ProductListControlPanel: typeof import('./components/product/ProductListControlPanel.vue')['default']
    ProductRow: typeof import('./components/product/ProductRow.vue')['default']
    ProductRowItem: typeof import('./components/product/ProductRowItem.vue')['default']
    ProductRowStatus: typeof import('./components/product/ProductRowStatus.vue')['default']
    ProductSettings: typeof import('./components/product/ProductSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
